### ISSUE TITLE
Add the rank question type

### ISSUE THREAD

**Issue by lognaturel** [getodk/web-forms#243]
## User stories
- As a form user, I want to change the relative position of items to express their ordering.
- As a form user, I don't want any risk of accidentally changing the relative position of items as I'm navigating through my form

User interested in using it: https://forum.getodk.org/t/select-multiple-choices-then-rank-the-selected-choices/16444/15?u=ln

## Design
Use a drag and drop interface as in Collect and Enketo: https://docs.getodk.org/form-question-types/#rank-widget. The goal here is to leverage the same design pattern with both Web Forms and Collect to create consistency in the user experience. 

We believe users won't accidentally move the items if we use the "hold and drag" interaction and exploring the arrows for keyboard users. In Collect, we display the rank options in a modal, but that involves more steps for the user, so we want to change it to be inline.

The closest component in the design system is the [reorder function]( https://primevue.org/datatable/#reorder ). If possible, we want to remove the header, add the drag icon to the row, and add a highlighted state when the user is moving the item. Something to play around with once we have a working prototype, is making the entire row moveable vs moving from the drag icon specifically. From the drag icon might be tricky for people to use with different access needs or large fingers. Ideally the "hold and drag" can happen anywhere on the option and that's is enough friction to prevent any mistakes.  

**Figma designs** - work in progress 🚧
- [Web Forms](https://www.figma.com/design/6v0NnvayfDlaQhYpjv37Bn/ODK-Web-Forms?node-id=847-19422&t=YsdgKLkYJsuM5Qbh-1)
- [Collect](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5772-59579&t=jPiVNxqXlewzjP6i-0)

## Out of scope
- clear state (we will work on this later)

## Notes
Component options:
* PrimeVue [OrderList](https://primevue.org/orderlist/), not the desired experience
* PrimeVue [reorderable table](https://primevue.org/datatable/#reorder), close to the desired experience but with table-like styling
* [vue-draggable-plus](https://vue-draggable-plus.pages.dev/en/demo/basic/#directive-usage)
* Port from Enketo

## Todo
- [ ] @lognaturel: refresh memory on why we introduced `odk:rank` as a type instead of using `string`. Maybe because any consumer needs to know that the string has semantics beyond a regular `string`? But the same could be said for select one|multiple. Make sure it's documented at https://getodk.github.io/xforms-spec/#data-types
- [ ] @alyblenkin: attach mockup specific to Web Forms
    - [x] How do we want to reduce the chance of accidental reordering when on a touch device? Enketo has an attempt with a "Click to start" but it doesn't address what happens after first data entry has been made and the user is still navigating the form. Mantine has [a version where the handle must be used](https://ui.mantine.dev/category/dnd/#dnd-list-handle).

**Comment by latin-panda** [comment]
The assignee and status fields are currently disabled for me, but I wanted to let you know that I'm working on this ticket, and the status is now 'In Progress.' I'll be opening a draft PR shortly to provide visibility into the incremental progress and to gather early feedback.

**Comment by latin-panda** [comment]
Update:
- This component will keep the `odk:rank` _bind type_, which is ultimately a `string`. No more types are introduced by now.
- The namespaced control/body element name (`<odk:rank>`) is correct, as ODK invented the rank, not from W3C XForms. 
- This component implementation is similar to multi-select, with the difference that the value keeps all the options, and the order is important. 
- Clear state (trash can icon) and `Click to start` aren't part of this iteration. 
- Each option has a drag indicator (icon) and arrow buttons. The option's width is fully extended to the screen size. 
- The arrow buttons are hidden on mobile devices, making them easier to use on smaller screens and allowing text to wrap less, contributing to better readability. 
- Hold and drag are anywhere in the option (not just the icon), making them easier to use. 
- The hold should last a few milliseconds to activate the drag and prevent accidental reordering. 

<img width="500" alt="Small screen Rank component" src="https://github.com/user-attachments/assets/301a6bed-1da2-4af1-8138-396c75be6844" />

<img width="250" alt="Small screen Rank component" src="https://github.com/user-attachments/assets/3eef18a9-f3b0-40c4-96cf-3682a97cb77b" />

Component implementation options:
- PrimeVue [OrderList](https://primevue.org/orderlist/) - Discarded, not the desired experience
- PrimeVue [Reorderable table](https://primevue.org/datatable/#reorder) - Discarded, it doesn't work in Android browsers ([known bug reported](https://github.com/primefaces/primevue/issues/5805))
- [vue-draggable-next](https://www.npmjs.com/package/vue-draggable-next) - Discarded, based on Sortable.js as vue-draggable-plus does, but it has fewer configurations and not so actively maintained by the community. 
- [vue-draggable-plus](https://vue-draggable-plus.pages.dev/en/demo/basic/#directive-usage) - Promising, it works in Android browsers and has the configuration we need to achieve the desired UX. It has an active community, and a Vue team member made it. Now, I'm testing it in more depth by implementing basic UX we need.
