### ISSUE TITLE
Epic: Submission edit

### ISSUE THREAD

**Issue by alyblenkin** [getodk/web-forms#247]
## User stories

As a project manager
I want to edit a submission 
So that I can adjust or fix any mistakes

## Sub-tasks related to this Epic 
More sub-tasks may be identified later in the implementation 
- [x] https://github.com/getodk/web-forms/issues/299
- [x] https://github.com/getodk/web-forms/issues/36
- [x] https://github.com/getodk/web-forms/issues/37
- [ ] https://github.com/getodk/web-forms/issues/314

**Comment by lognaturel** [comment]
Now that #355 is in and released, let's close this! #314 feels like it stands alone. We may want to track it as part of a different epic that's more like "communicate WF state to user" that would involve indicating when a form is a preview, edits, etc.
