### ISSUE TITLE
Epic: add support for media as part of question and choice labels

### ISSUE THREAD

**Issue by lognaturel** [getodk/web-forms#30]
## User Story

As a form designer
I want to be able to define form fields that use attached media
So that I can show images, play audio, play videos, etc

- [x] [image labels for choices](https://github.com/getodk/web-forms/issues/347)
- [x] [image labels for questions](https://github.com/getodk/web-forms/issues/525)
- [x] [audio labels for questions](https://github.com/getodk/web-forms/issues/607)
- [x] [video labels for questions](https://github.com/getodk/web-forms/issues/608)
- [x] [audio labels for choices](https://github.com/getodk/web-forms/issues/607)
- [x] [video labels for choices](https://github.com/getodk/web-forms/issues/608)
- [ ] ~Image, audio, video labels for Rank's options~ [[Removed](https://github.com/getodk/web-forms/issues/30#issuecomment-3986199008)]

**Comment by latin-panda** [comment]
> Image, audio, video labels for Rank's options

Removing this from the Epic and waiting to hear about more user stories that need this feature ([team thread](https://getodk.slack.com/archives/C051L6AKG4F/p1772143269093669)).

**Comment by garethbowen** [comment]
@latin-panda Does this mean we can mark the image, audio, and video features as done in the feature matrix? These lines specifically: https://github.com/getodk/web-forms/blob/dabf2738271ae5cd77168f3c9291d423c62a790a/feature-matrix.json#L122-L125
